import "@hotwired/turbo-rails"
import "controllers"
import "@popperjs/core"
import "bootstrap"
import "controllers/toggle_form"
import "mapbox-gl"
import "@mapbox/mapbox-gl-geocoder"
import "controllers/address_autocomplete_controller"
